### ISSUE TITLE
week 7 assignment 

### ISSUE THREAD

**Issue by Joeifesi** [ds4owd-001/md-07-assignments-Joeifesi#1]
![Af](https://github.com/ds4owd-001/md-07-assignments-Joeifesi/assets/147097762/9943e684-53d0-43fe-9221-603065fc6244)
PLEASE I NEED HELP WITH THIS. I WAS  PRACTICING AND THIS HAPPENED I CANNOT LOG IN.
![Ag](https://github.com/ds4owd-001/md-07-assignments-Joeifesi/assets/147097762/6ee4540c-e17f-44c7-91ce-436fd3305e43)
I WAS AT THIS STAGE AND OPENED GIT ON R STUDIO, WHEN I TRIED TO SELECT ALL FILES  I MADE A MISTAKE . HOW DO I GET BACK TO R STUDIO AND MY FILES.
@larnsce @mianzg @sskorik01

**Comment by Joeifesi** [comment]
Issue resolved.

**Comment by larnsce** [comment]
Well done, happy to hear that you could sort it out yourself.

**Comment by Joeifesi** [comment]
I WAS NOT ABLE TO RESOLVE THE ISSUES WRITTEN IN RED error path does not
exist . please i need help to resolve
 this issue.
